services:
  db:
    image: postgres:14
    container_name: taskmanager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    image: my-task-backend
    container_name: taskmanager-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/taskmanager
    ports:
      - '5001:5000'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://localhost:5000/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
