name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'
      - 'libs/**'
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/backend/**'
      - 'libs/**'
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - '.github/workflows/backend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate --schema=apps/backend/prisma/schema.prisma

      - name: Lint backend
        run: npx nx lint backend

      - name: Run backend tests
        run: npx nx test backend --ci --code-coverage

      - name: Run integration tests
        run: npx jest apps/backend/__integration-tests__ --runInBand

      - name: Build backend
        run: npx nx build backend

  docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get version from backend/package.json
        id: version
        run: echo "version=$(jq -r .version apps/backend/package.json)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: |
            robinwinters/task-management-app:latest
            robinwinters/task-management-app:${{ steps.version.outputs.version }}
